[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  python_version = "3.8"

[[redirects]]
  from = "/api/metrics/*"
  to = "/.netlify/functions/metrics/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"